---
stages:
  data_ingestion:
    cmd: python src/customer_churn/pipelines/pipe_01_data_ingestion.py
    deps:
      - src/customer_churn/pipelines/pipe_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/churndb.csv
      - artifacts/data_ingestion/metadata.json