---
stages:
  data_ingestion:
    cmd: python src/customer_churn/pipelines/pipe_01_data_ingestion.py
    deps:
      - src/customer_churn/pipelines/pipe_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/churndb.csv
      - artifacts/data_ingestion/metadata.json

  data_validation:
    cmd: python src/customer_churn/pipelines/pipe_02_data_validation.py
    deps:
      - src/customer_churn/pipelines/pipe_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/churndb.csv
    outs:
      - artifacts/data_validation/status.json

  data_transformation:
    cmd: python src/customer_churn/pipelines/pipe_03_data_transformation.py
    deps:
      - src/customer_churn/pipelines/pipe_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/X_test_transformed.joblib
      - artifacts/data_transformation/y_test.csv
      - artifacts/data_transformation/X_train_transformed.joblib
      - artifacts/data_transformation/y_train.csv
      - artifacts/data_transformation/X_val_transformed.joblib
      - artifacts/data_transformation/y_val.csv