artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  mongo_uri: mongodb+srv://username:password@mychurndb.bjfry.mongodb.net/
  database_name: customer_churn
  collection_name: transformed_churndb


data_validation:
  root_dir: artifacts/data_validation
  data_source: artifacts/data_ingestion/churndb.csv
  status_file: artifacts/data_validation/status.json
  critical_columns:
    - 'age'
    - 'gender'
    - 'region_category'
    - 'membership_category'
    - 'joined_through_referral'
    - 'preferred_offer_types'
    - 'medium_of_operation'
    - 'internet_option'
    - 'recency'
    - 'avg_time_spent'
    - 'monetary'
    - 'frequency'
    - 'points_in_wallet' 
    - 'used_special_discount'
    - 'offer_application_preference'
    - 'past_complaint'
    - 'complaint_status'
    - 'feedback'
    - 'churn_risk_score'
    - 'tenure_months'
    - 'visit_hour' 
    - 'login_spend_ratio'
    - 'login_transaction_ratio'


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/churndb.csv
  numerical_cols:
    - 'age'
    - 'recency'
    - 'avg_time_spent'
    - 'monetary'
    - 'frequency'
    - 'points_in_wallet' 
    - 'tenure_months'
    - 'visit_hour' 
    - 'login_spend_ratio'
    - 'login_transaction_ratio'
                  
  categorical_cols:
    - 'gender'
    - 'region_category'
    - 'membership_category'
    - 'joined_through_referral'
    - 'preferred_offer_types'
    - 'medium_of_operation'
    - 'internet_option'
    - 'used_special_discount'
    - 'offer_application_preference'
    - 'past_complaint'
    - 'complaint_status'
    - 'feedback'
    
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/X_train_transformed.joblib
  val_data_path: artifacts/data_transformation/X_val_transformed.joblib
  model_name: model.joblib
  mlflow_uri: https://dagshub.com/Sanju-Shrestha/Customer-Churn-Prediction.mlflow