artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  mongo_uri: mongodb+srv://username:password@mychurndb.bjfry.mongodb.net/
  database_name: customer_churn
  collection_name: transformed_churndb
